export const TOTAL_STEPS = 24;

export const STEPS = [
  { id: 1, title: 'Welcome', shortTitle: 'Intro', part: 0 },
  { id: 2, title: 'The Confidence Machine', shortTitle: 'Confidence', part: 1 },
  { id: 3, title: 'Patterns Building on Patterns', shortTitle: 'Patterns', part: 1 },
  { id: 4, title: 'Weights: How the Network Decides What Matters', shortTitle: 'Weights', part: 1 },
  { id: 5, title: 'How a Network Learns', shortTitle: 'Learning', part: 1 },
  { id: 6, title: 'The Road Ahead', shortTitle: 'Road Ahead', part: 1 },
  { id: 7, title: 'What is a Neuron Truly?', shortTitle: 'Neuron Intro', part: 2 },
  { id: 8, title: 'Normalization', shortTitle: 'Data & Inputs', part: 2 },
  { id: 9, title: 'Weights: How Much Each Factor Matters', shortTitle: 'Weights', part: 2 },
  { id: 10, title: 'Bias: Adding Flexibility', shortTitle: 'Bias', part: 2 },
  { id: 11, title: 'Computing Pre-activation', shortTitle: 'Pre-activation', part: 2 },
  { id: 12, title: 'The Sigmoid Function Pt. 1', shortTitle: 'Sigmoid Pt. 1', part: 2 },
  { id: 13, title: 'The Sigmoid Function Pt. 2', shortTitle: 'Sigmoid Pt. 2', part: 2 },
  { id: 14, title: 'The Sigmoid Function Pt. 3', shortTitle: 'Sigmoid Pt. 3', part: 2 },
  { id: 15, title: 'The Sigmoid Function Pt. 4', shortTitle: 'Sigmoid Pt. 4', part: 2 },
  { id: 16, title: 'Your First Complete Neuron', shortTitle: 'Complete Neuron', part: 2 },
  { id: 17, title: 'How Information Flows Through a Network', shortTitle: 'Network Flow', part: 2 },
  { id: 18, title: 'Building a Layer of Neurons', shortTitle: 'Layers', part: 2 },
  { id: 19, title: 'Connecting Layers', shortTitle: 'Connecting', part: 2 },
  { id: 20, title: 'Forward Propagation', shortTitle: 'Forward Pass', part: 2 },
  { id: 21, title: 'Measuring Error: The Loss Function', shortTitle: 'Loss', part: 2 },
  { id: 22, title: 'Derivatives and Gradients', shortTitle: 'Derivatives', part: 2 },
  { id: 23, title: 'Backpropagation', shortTitle: 'Backprop', part: 2 },
  { id: 24, title: 'Gradient Descent & Training', shortTitle: 'Training', part: 2 },
];
