'use client';

import ExplanationBox from '@/components/ExplanationBox';
import MathFormula from '@/components/MathFormula';
import WorkedExample from '@/components/WorkedExample';
import CalcStep from '@/components/CalcStep';
import CodeBlock from '@/components/CodeBlock';

export default function Step4() {
  return (
    <div>
      <ExplanationBox title="Correlation Is Not Causation — and It Matters">
        <p>
          A classic example: ice cream sales and drowning rates are strongly correlated. A model
          trained on this data might recommend reducing ice cream sales to prevent drownings.
          The actual cause of both is a third variable — hot weather drives people to both swim
          and eat ice cream. That third variable, hidden from the model, is called a
          <strong> confounder</strong>.
        </p>
        <p>
          Standard ML is designed to find correlations. Given enough data, it will find every
          pattern — causal and spurious alike — and exploit whichever ones predict the training
          labels best. When a correlation is stable across all deployments, that is fine.
          But the moment we <em>intervene</em> on the world — change a policy, administer a
          treatment, make a decision — we need to know what will causally happen, not just
          what is statistically associated.
        </p>
      </ExplanationBox>

      <ExplanationBox title="Structural Causal Models">
        <p>
          A <strong>Structural Causal Model (SCM)</strong> represents the data-generating process
          as a directed acyclic graph (DAG) where each node is a variable and each directed edge
          represents a direct causal influence. Each variable X_i is assigned by a structural
          equation: X_i = f_i(parents(X_i), noise_i). The noise terms are independent across
          variables — that independence is what makes the causal structure meaningful.
        </p>
        <p>
          The DAG encodes <em>which variables directly cause which others</em>. Observational data
          is generated by letting all variables take their natural values under these equations.
          But causal reasoning requires two additional operations that go beyond observation.
        </p>
      </ExplanationBox>

      <ExplanationBox title="The Do-Operator: Interventions">
        <p>
          Pearl&apos;s <strong>do-operator</strong> formalizes an intervention: do(X = x) means we
          <em>set</em> X to the value x by external action, severing all incoming arrows to X
          in the DAG. This is fundamentally different from conditioning on X = x (which just
          filters observed data to cases where X happened to equal x).
        </p>
        <p>
          The difference matters enormously. In the ice cream example:
        </p>
        <ul style={{ lineHeight: '1.8' }}>
          <li>P(drowning | ice cream = high) is high — because both are caused by hot weather.</li>
          <li>P(drowning | do(ice cream = high)) is the same as baseline — forcing people to buy
          ice cream has no effect on drownings because we severed the confounding path through weather.</li>
        </ul>
      </ExplanationBox>

      <MathFormula label="Interventional vs Observational Distribution">
        P(Y | do(X = x)) vs P(Y | X = x)
      </MathFormula>

      <ExplanationBox title="Counterfactual Reasoning">
        <p>
          Counterfactuals go one level deeper than interventions. While an intervention asks
          &quot;if we set X to x in the population, what happens to Y?&quot;, a counterfactual asks
          &quot;for <em>this specific individual</em>, who received X = 0, what would Y have been
          if they had received X = 1 instead?&quot;
        </p>
        <p>
          Counterfactuals require reasoning about a specific noise realization — the unique
          circumstances of one individual — while changing one variable. They are the foundation
          of individual-level fairness analysis (&quot;would this person have been denied the loan
          if they were a different race?&quot;) and personal-level medical reasoning (&quot;did this
          drug cause this patient&apos;s recovery?&quot;).
        </p>
        <p>
          Answering counterfactuals requires a full SCM — not just the graph structure but
          the actual functional equations — because we need to propagate the individual&apos;s
          noise values through the modified model. This is strictly more information than
          what observational data alone provides.
        </p>
      </ExplanationBox>

      <ExplanationBox title="Why ML Needs Causality">
        <p>
          Four concrete failure modes that causality addresses:
        </p>
        <ul style={{ lineHeight: '1.8' }}>
          <li><strong>Distribution shift:</strong> A model trained on observational data fails
          when deployed in an environment where the confounders change. Causal models are
          stable across environments because they encode mechanisms, not correlations.</li>
          <li><strong>Spurious features:</strong> A model predicts pneumonia survival partly from
          &quot;was the patient admitted to ICU?&quot; — because sicker patients go to the ICU and sicker
          patients die more. This is a confounder. Acting on it (admitting healthier patients
          to avoid ICU) would be harmful.</li>
          <li><strong>Policy evaluation:</strong> Deciding whether to roll out a new algorithm
          across a platform requires estimating the causal effect of the intervention, not
          the correlation between current algorithm choice and outcomes.</li>
          <li><strong>Fairness:</strong> Some legal standards require counterfactual fairness —
          would the decision have changed if the individual&apos;s protected attribute were different?
          That is a causal question, not a statistical one.</li>
        </ul>
      </ExplanationBox>

      <ExplanationBox title="In Python">
        <p>The snippet below computes the na&iuml;ve (confounded) estimate and the
        backdoor-adjusted (causal) estimate from a small tabular dataset,
        showing exactly how stratification removes the confounder.</p>
      </ExplanationBox>

      <CodeBlock
        filename="backdoor_adjustment.py"
        caption="Backdoor adjustment: stratify over the confounder Z to recover the true causal effect of X on Y."
        code={`import numpy as np

# -------------------------------------------------------------------
# Backdoor Adjustment — estimating P(Y | do(X)) from observational data
#
# DAG:  Z -> X  (confounder causes treatment)
#       Z -> Y  (confounder also causes outcome)
#       X -> Y  (treatment may causally affect outcome)
#
# Problem: older patients (Z=1) are more likely to get the drug (X=1)
#          AND more likely to recover (Y=1), inflating the raw correlation.
# -------------------------------------------------------------------

# Small dataset: each row is (Z=age_old, X=got_drug, Y=recovered).
# 0 = young/no-drug/not-recovered, 1 = old/got-drug/recovered
data = np.array([
    # Z, X, Y
    [0, 0, 0],  # young, no drug, no recovery
    [0, 0, 0],
    [0, 1, 0],  # young, got drug, still no recovery
    [0, 1, 0],
    [1, 0, 1],  # old, no drug, recovered (age helps)
    [1, 0, 1],
    [1, 1, 1],  # old, got drug, recovered
    [1, 1, 1],
    [1, 1, 1],
])

Z = data[:, 0]
X = data[:, 1]
Y = data[:, 2]

# --- Naive (confounded) estimate ------------------------------------
# P(Y=1 | X=1): just look at rows where the drug was given.
# This picks up age as a hidden confound, so it OVER-estimates the drug effect.
naive_treated   = Y[X == 1].mean()  # recovery rate among drug receivers
naive_untreated = Y[X == 0].mean()  # recovery rate among non-receivers
naive_effect = naive_treated - naive_untreated
print(f"Naive effect (confounded): {naive_effect:.3f}")
# Will be positive even if the drug does nothing, because old patients
# (Z=1) received the drug more often AND recover more due to age.

# --- Backdoor-adjusted (causal) estimate ----------------------------
# Formula: P(Y | do(X=x)) = sum_z  P(Y | X=x, Z=z) * P(Z=z)
# We stratify by Z, compute the conditional outcome, then re-weight
# by the MARGINAL distribution of Z (not its conditional given X).
z_values = np.unique(Z)
p_z = np.array([(Z == z).mean() for z in z_values])  # P(Z=z)

def cond_mean(x_val, z_val):
    # E[Y | X=x_val, Z=z_val] — outcome rate in this stratum
    mask = (X == x_val) & (Z == z_val)
    if mask.sum() == 0:
        return 0.0  # no data in this cell; assume 0 (or use prior)
    return Y[mask].mean()

# Weighted sum over strata — this removes the confounding path Z->X.
p_y_do1 = sum(cond_mean(1, z) * p_z[i] for i, z in enumerate(z_values))
p_y_do0 = sum(cond_mean(0, z) * p_z[i] for i, z in enumerate(z_values))

causal_effect = p_y_do1 - p_y_do0
print(f"Backdoor-adjusted causal effect: {causal_effect:.3f}")
# When the drug truly has no effect (as in this dataset), this returns ~0.
# The naive estimate was misleading; the adjusted estimate is correct.`}
      />

      <WorkedExample title="Identifying a Causal Effect via Adjustment">
        <p>
          Suppose we want to know the causal effect of a medication X on recovery Y, but
          age Z is a confounder: older patients are both more likely to receive the drug and
          more likely to recover anyway.
        </p>
        <CalcStep number={1}>Observe the DAG: Z causes X and Z causes Y. X also causes Y.</CalcStep>
        <CalcStep number={2}>
          Na&iuml;ve estimate P(Y=1 | X=1) = 0.80 vs P(Y=1 | X=0) = 0.60. Looks like a large effect.
        </CalcStep>
        <CalcStep number={3}>
          Stratify by age: Among young patients (Z=0), P(Y|X=1, Z=0) = 0.50, P(Y|X=0, Z=0) = 0.50.
          Among old patients (Z=1), P(Y|X=1, Z=1) = 0.90, P(Y|X=0, Z=1) = 0.90.
        </CalcStep>
        <CalcStep number={4}>
          The backdoor adjustment formula: P(Y | do(X=x)) = sum_z P(Y | X=x, Z=z) P(Z=z).
          Suppose P(Z=1) = 0.6. Then P(Y | do(X=1)) = 0.50(0.4) + 0.90(0.6) = 0.20 + 0.54 = 0.74.
          Similarly P(Y | do(X=0)) = 0.50(0.4) + 0.90(0.6) = 0.74.
        </CalcStep>
        <p style={{ marginTop: '1rem' }}>
          After controlling for the confounder, the causal effect is zero — the drug does nothing.
          The apparent 20-point improvement was entirely due to older patients (who recover more)
          receiving the drug more often. Ignoring causality would have led to a costly and
          ineffective treatment recommendation.
        </p>
      </WorkedExample>
    </div>
  );
}
