'use client';

import ExplanationBox from '@/components/ExplanationBox';
import MathFormula from '@/components/MathFormula';
import WorkedExample from '@/components/WorkedExample';
import CalcStep from '@/components/CalcStep';

export default function Step4() {
  return (
    <div>
      <ExplanationBox title="Correlation Is Not Causation — and It Matters">
        <p>
          A classic example: ice cream sales and drowning rates are strongly correlated. A model
          trained on this data might recommend reducing ice cream sales to prevent drownings.
          The actual cause of both is a third variable — hot weather drives people to both swim
          and eat ice cream. That third variable, hidden from the model, is called a
          <strong> confounder</strong>.
        </p>
        <p>
          Standard ML is designed to find correlations. Given enough data, it will find every
          pattern — causal and spurious alike — and exploit whichever ones predict the training
          labels best. When a correlation is stable across all deployments, that is fine.
          But the moment we <em>intervene</em> on the world — change a policy, administer a
          treatment, make a decision — we need to know what will causally happen, not just
          what is statistically associated.
        </p>
      </ExplanationBox>

      <ExplanationBox title="Structural Causal Models">
        <p>
          A <strong>Structural Causal Model (SCM)</strong> represents the data-generating process
          as a directed acyclic graph (DAG) where each node is a variable and each directed edge
          represents a direct causal influence. Each variable X_i is assigned by a structural
          equation: X_i = f_i(parents(X_i), noise_i). The noise terms are independent across
          variables — that independence is what makes the causal structure meaningful.
        </p>
        <p>
          The DAG encodes <em>which variables directly cause which others</em>. Observational data
          is generated by letting all variables take their natural values under these equations.
          But causal reasoning requires two additional operations that go beyond observation.
        </p>
      </ExplanationBox>

      <ExplanationBox title="The Do-Operator: Interventions">
        <p>
          Pearl&apos;s <strong>do-operator</strong> formalizes an intervention: do(X = x) means we
          <em>set</em> X to the value x by external action, severing all incoming arrows to X
          in the DAG. This is fundamentally different from conditioning on X = x (which just
          filters observed data to cases where X happened to equal x).
        </p>
        <p>
          The difference matters enormously. In the ice cream example:
        </p>
        <ul style={{ lineHeight: '1.8' }}>
          <li>P(drowning | ice cream = high) is high — because both are caused by hot weather.</li>
          <li>P(drowning | do(ice cream = high)) is the same as baseline — forcing people to buy
          ice cream has no effect on drownings because we severed the confounding path through weather.</li>
        </ul>
      </ExplanationBox>

      <MathFormula label="Interventional vs Observational Distribution">
        P(Y | do(X = x)) vs P(Y | X = x)
      </MathFormula>

      <ExplanationBox title="Counterfactual Reasoning">
        <p>
          Counterfactuals go one level deeper than interventions. While an intervention asks
          &quot;if we set X to x in the population, what happens to Y?&quot;, a counterfactual asks
          &quot;for <em>this specific individual</em>, who received X = 0, what would Y have been
          if they had received X = 1 instead?&quot;
        </p>
        <p>
          Counterfactuals require reasoning about a specific noise realization — the unique
          circumstances of one individual — while changing one variable. They are the foundation
          of individual-level fairness analysis (&quot;would this person have been denied the loan
          if they were a different race?&quot;) and personal-level medical reasoning (&quot;did this
          drug cause this patient&apos;s recovery?&quot;).
        </p>
        <p>
          Answering counterfactuals requires a full SCM — not just the graph structure but
          the actual functional equations — because we need to propagate the individual&apos;s
          noise values through the modified model. This is strictly more information than
          what observational data alone provides.
        </p>
      </ExplanationBox>

      <ExplanationBox title="Why ML Needs Causality">
        <p>
          Four concrete failure modes that causality addresses:
        </p>
        <ul style={{ lineHeight: '1.8' }}>
          <li><strong>Distribution shift:</strong> A model trained on observational data fails
          when deployed in an environment where the confounders change. Causal models are
          stable across environments because they encode mechanisms, not correlations.</li>
          <li><strong>Spurious features:</strong> A model predicts pneumonia survival partly from
          &quot;was the patient admitted to ICU?&quot; — because sicker patients go to the ICU and sicker
          patients die more. This is a confounder. Acting on it (admitting healthier patients
          to avoid ICU) would be harmful.</li>
          <li><strong>Policy evaluation:</strong> Deciding whether to roll out a new algorithm
          across a platform requires estimating the causal effect of the intervention, not
          the correlation between current algorithm choice and outcomes.</li>
          <li><strong>Fairness:</strong> Some legal standards require counterfactual fairness —
          would the decision have changed if the individual&apos;s protected attribute were different?
          That is a causal question, not a statistical one.</li>
        </ul>
      </ExplanationBox>

      <WorkedExample title="Identifying a Causal Effect via Adjustment">
        <p>
          Suppose we want to know the causal effect of a medication X on recovery Y, but
          age Z is a confounder: older patients are both more likely to receive the drug and
          more likely to recover anyway.
        </p>
        <CalcStep number={1}>Observe the DAG: Z causes X and Z causes Y. X also causes Y.</CalcStep>
        <CalcStep number={2}>
          Na&iuml;ve estimate P(Y=1 | X=1) = 0.80 vs P(Y=1 | X=0) = 0.60. Looks like a large effect.
        </CalcStep>
        <CalcStep number={3}>
          Stratify by age: Among young patients (Z=0), P(Y|X=1, Z=0) = 0.50, P(Y|X=0, Z=0) = 0.50.
          Among old patients (Z=1), P(Y|X=1, Z=1) = 0.90, P(Y|X=0, Z=1) = 0.90.
        </CalcStep>
        <CalcStep number={4}>
          The backdoor adjustment formula: P(Y | do(X=x)) = sum_z P(Y | X=x, Z=z) P(Z=z).
          Suppose P(Z=1) = 0.6. Then P(Y | do(X=1)) = 0.50(0.4) + 0.90(0.6) = 0.20 + 0.54 = 0.74.
          Similarly P(Y | do(X=0)) = 0.50(0.4) + 0.90(0.6) = 0.74.
        </CalcStep>
        <p style={{ marginTop: '1rem' }}>
          After controlling for the confounder, the causal effect is zero — the drug does nothing.
          The apparent 20-point improvement was entirely due to older patients (who recover more)
          receiving the drug more often. Ignoring causality would have led to a costly and
          ineffective treatment recommendation.
        </p>
      </WorkedExample>
    </div>
  );
}
