'use client';

import ExplanationBox from '@/components/ExplanationBox';
import MathFormula from '@/components/MathFormula';
import WorkedExample from '@/components/WorkedExample';
import CalcStep from '@/components/CalcStep';

export default function Step4() {
  return (
    <div>
      <ExplanationBox title="Soft Clustering: Probabilities Instead of Hard Labels">
        <p>
          Every method so far assigns each point to <em>exactly one</em> cluster. But
          real data is messy. A customer who spends moderately and shops at medium
          frequency might genuinely belong 60% to the &quot;deal-seeker&quot; segment and
          40% to the &quot;casual browser&quot; segment. <strong>Gaussian Mixture Models</strong>{' '}
          (GMMs) capture this ambiguity by assigning every point a <strong>probability
          of belonging to each cluster</strong> rather than a single hard label.
        </p>
      </ExplanationBox>

      <ExplanationBox title="The Model: A Mixture of Gaussians">
        <p>
          A GMM assumes the data was generated by k Gaussian (normal) distributions mixed
          together. Each Gaussian component c has three parameters:
        </p>
        <ul style={{ lineHeight: '1.9' }}>
          <li>
            <strong>Mean (mu_c)</strong> — the center of the cluster, analogous to the
            centroid in k-means.
          </li>
          <li>
            <strong>Covariance (Sigma_c)</strong> — describes the shape and orientation
            of the cluster. A diagonal covariance gives axis-aligned ellipses; a full
            covariance gives tilted ellipses. K-means is a special case where all
            covariances are equal spheres.
          </li>
          <li>
            <strong>Mixing weight (pi_c)</strong> — the prior probability that a randomly
            drawn point came from component c. All weights sum to 1.
          </li>
        </ul>
      </ExplanationBox>

      <MathFormula label="GMM probability of a data point x">
        p(x) = sum over c from 1 to k of: pi_c * N(x | mu_c, Sigma_c)
      </MathFormula>

      <ExplanationBox title="The EM Algorithm: Learning the Parameters">
        <p>
          We cannot directly maximize the likelihood of the data because we don&apos;t
          know which component generated each point. The{' '}
          <strong>Expectation-Maximization (EM)</strong> algorithm elegantly handles
          this by alternating two steps until convergence:
        </p>
        <p>
          <strong>E-step (Expectation)</strong> — given the current parameter estimates,
          compute the <em>responsibility</em> r(c, x): the posterior probability that
          component c generated point x. This is just Bayes&apos; rule applied to each
          point against each component.
        </p>
        <p>
          <strong>M-step (Maximization)</strong> — treat the responsibilities as soft
          counts and refit each Gaussian. The new mean mu_c is the responsibility-weighted
          average of all points. The new covariance Sigma_c is the responsibility-weighted
          scatter matrix. The new mixing weight pi_c is the average responsibility across
          all points.
        </p>
        <p>
          Each full E+M cycle is guaranteed to increase (or maintain) the log-likelihood
          of the data. The algorithm converges to a local optimum, so it is common to run
          it multiple times from different initializations.
        </p>
      </ExplanationBox>

      <MathFormula label="E-step: responsibility of component c for point x">
        r(c, x) = (pi_c * N(x | mu_c, Sigma_c)) / (sum over j of pi_j * N(x | mu_j, Sigma_j))
      </MathFormula>

      <MathFormula label="M-step: updated mean for component c">
        mu_c (new) = (sum over all x of r(c, x) * x) / (sum over all x of r(c, x))
      </MathFormula>

      <WorkedExample title="One EM Iteration with Two Components">
        <p>
          Two customer clusters (k = 2), one feature: normalized monthly spend x.
          Current parameters: mu_1 = 0.3, mu_2 = 0.8, pi_1 = 0.5, pi_2 = 0.5
          (simplified: treat each Gaussian as having sigma = 0.2 so N values are
          proportional to exp(-(x - mu)^2 / 0.08)).
        </p>
        <p>
          Focus on one customer: x = 0.6 (moderate spender).
        </p>
        <CalcStep number={1}>
          Unnormalized responsibility for component 1:
          pi_1 * N(0.6 | 0.3, 0.2) proportional to 0.5 * exp(-(0.6-0.3)^2 / 0.08)
          = 0.5 * exp(-0.09/0.08) = 0.5 * exp(-1.125) ≈ 0.5 * 0.3247 = 0.1623
        </CalcStep>
        <CalcStep number={2}>
          Unnormalized responsibility for component 2:
          pi_2 * N(0.6 | 0.8, 0.2) proportional to 0.5 * exp(-(0.6-0.8)^2 / 0.08)
          = 0.5 * exp(-0.04/0.08) = 0.5 * exp(-0.5) ≈ 0.5 * 0.6065 = 0.3033
        </CalcStep>
        <CalcStep number={3}>
          Total: 0.1623 + 0.3033 = 0.4656
        </CalcStep>
        <CalcStep number={4}>
          r(1, x=0.6) = 0.1623 / 0.4656 ≈ 0.348
        </CalcStep>
        <CalcStep number={5}>
          r(2, x=0.6) = 0.3033 / 0.4656 ≈ 0.652
        </CalcStep>
        <p style={{ marginTop: '1rem' }}>
          This customer is assigned 34.8% to the low-spend cluster and 65.2% to the
          high-spend cluster. In the M-step, this point contributes 0.652 times its
          value (0.6) to the update of mu_2 and only 0.348 times to mu_1 — a weighted
          pull rather than a binary assignment.
        </p>
      </WorkedExample>

      <ExplanationBox title="How GMM Generalizes K-Means">
        <p>
          K-means is mathematically a special case of EM for GMMs where all covariances
          are forced to be equal spheres (sigma^2 * I) and the responsibilities are
          &quot;hardened&quot; to 0 or 1 (winner-takes-all assignment). GMM relaxes both
          constraints: clusters can have different shapes, orientations, and sizes, and
          every point contributes to every cluster in proportion to how likely it is to
          have come from there. That softness is exactly what makes GMMs powerful for
          overlapping segments.
        </p>
      </ExplanationBox>

    </div>
  );
}
