'use client';

import ExplanationBox from '@/components/ExplanationBox';
import MathFormula from '@/components/MathFormula';
import WorkedExample from '@/components/WorkedExample';
import CalcStep from '@/components/CalcStep';

export default function Step7() {
  return (
    <div>
      <ExplanationBox title="What Is an Anomaly?">
        <p>
          An <strong>anomaly</strong> (also called an outlier) is a point that differs so
          much from the rest of the data that it seems to have been generated by a
          different process. In the customer dataset, a user who makes 500 tiny transactions
          per day, or one who purchases exclusively from a single obscure category for one
          month and then never returns, stands apart from the 49,998 who follow more
          predictable patterns. That divergence is the signal anomaly detection tries to
          catch.
        </p>
        <p>
          Real-world use cases include credit card fraud, industrial equipment failure,
          network intrusion, medical diagnosis, and data-quality auditing.
        </p>
      </ExplanationBox>

      <ExplanationBox title="Density-Based and Distance-Based Methods">
        <p>
          The simplest anomaly detectors ask: <em>is this point in a sparse region?</em>
        </p>
        <p>
          <strong>Distance-based:</strong> a point is an outlier if its distance to its
          k-th nearest neighbor is unusually large compared to most other points. Compute
          the k-NN distance for every point; points in the tail of that distribution are
          flagged. In our customer data, a customer whose 5 nearest neighbors are still
          very far away is likely anomalous.
        </p>
        <p>
          <strong>Local Outlier Factor (LOF)</strong> refines this by comparing the local
          density around a point to the densities of its neighbors. A point in a
          low-density region surrounded by high-density neighbors gets a high LOF score,
          even if its absolute distance to neighbors is not extreme. This handles datasets
          where normal clusters have very different densities.
        </p>
      </ExplanationBox>

      <MathFormula label="Local Reachability Density (used in LOF)">
        lrd(p) = 1 / (avg over neighbors q of: max(dist(p,q), k-dist(q)))
      </MathFormula>

      <ExplanationBox title="Isolation Forest: Anomalies Are Easy to Isolate">
        <p>
          <strong>Isolation Forest</strong> takes a completely different approach. Instead
          of measuring density, it exploits a key observation: <em>anomalous points are
          rare and different</em>, so they are isolated by random cuts much faster than
          normal points.
        </p>
        <p>
          The algorithm builds an ensemble of random decision trees (an &quot;isolation
          forest&quot;). Each tree is constructed by repeatedly picking a random feature
          and a random split value until every point is isolated in its own leaf. Anomalous
          points require <em>fewer splits</em> to isolate because they are far from the
          crowd. The anomaly score of a point is inversely proportional to the average
          depth at which it gets isolated across all trees.
        </p>
        <p>
          Isolation Forest scales to very large datasets, requires no distance calculations,
          and handles high-dimensional data well — making it one of the most practical
          anomaly detectors in production systems.
        </p>
      </ExplanationBox>

      <MathFormula label="Isolation Forest anomaly score">
        score(x) = 2^(-(avg path length for x) / c(n))
        where c(n) is the expected path length for a dataset of size n
      </MathFormula>

      <WorkedExample title="Spotting a Fraudulent Customer with Path Depth">
        <p>
          An isolation forest with 100 trees is trained on 50,000 customers.
          We check two customers: Alice (typical buyer) and Bob (suspected fraud).
        </p>
        <CalcStep number={1}>
          Alice&apos;s average isolation depth across 100 trees: 14.2 splits.
        </CalcStep>
        <CalcStep number={2}>
          Bob&apos;s average isolation depth: 3.1 splits.
        </CalcStep>
        <CalcStep number={3}>
          Expected average depth for n = 50,000: c(50000) ≈ 2 * (ln(49999) + 0.5772) - 2*49999/50000 ≈ 22.8
        </CalcStep>
        <CalcStep number={4}>
          Alice&apos;s score: 2^(-(14.2 / 22.8)) = 2^(-0.623) ≈ 0.649 (normal range)
        </CalcStep>
        <CalcStep number={5}>
          Bob&apos;s score: 2^(-(3.1 / 22.8)) = 2^(-0.136) ≈ 0.909 (high — anomaly)
        </CalcStep>
        <p style={{ marginTop: '1rem' }}>
          Scores near 1.0 indicate anomalies; scores near 0.5 indicate normal points.
          Bob&apos;s score of 0.909 would trigger a fraud review flag. Alice&apos;s 0.649
          is safely in the normal range.
        </p>
      </WorkedExample>

      <ExplanationBox title="Reconstruction Error: Autoencoders">
        <p>
          A third family of anomaly detectors uses deep learning. An
          <strong> autoencoder</strong> is a neural network trained to compress its input
          to a small bottleneck (encoding) and then reconstruct the original input from
          that encoding. It is trained on normal data only. At inference time, normal
          points reconstruct well (low reconstruction error) because the network has seen
          similar patterns. Anomalous points reconstruct poorly (high reconstruction error)
          because the bottleneck cannot represent their unusual patterns. The reconstruction
          error serves as the anomaly score.
        </p>
        <p>
          Autoencoders are especially powerful for high-dimensional inputs like images
          (detecting defective products on a manufacturing line) or time series (detecting
          unusual network traffic patterns).
        </p>
      </ExplanationBox>
    </div>
  );
}
